# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a79c69901feb72bf01790b6a04c9fda1ebc4ce40f20aec6757f4292ed981d8cabc261d7ef9db270faff3dc0a1b2f33f7a4147f80804431218c27fbe117fa208

test:
  secret_key_base: 99eaa0bcfea68dedbfd0aa7de0c271b7c3b66c7080c8d196c1fdb7044143f7e8254057874e1cca074a14731e2b17f5ed614faba35d1e0f259fdce63cfa50e583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
